=== Human-and-Cat/Jilyak-in-organization/XML/xml_2/spec.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="SPECIALIZATION">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="POIT">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="UNIVERSITY" type="xs:string" />
							<xs:element name="PASSING">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="BUDGET" type="xs:integer" />
										<xs:element name="PAY" type="xs:integer" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PAGES" type="xs:integer" />
							<xs:element name="CITY" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Human-and-Cat/Jilyak-in-organization/XML/xml_2/XML_L2_Shema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
	<SPECIALIZATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spec.xsd">
		<POIT>
			<UNIVERSITY>Гомельский государственный университет им. Ф. Скорины</UNIVERSITY>
			<PASSING>
				<BUDGET>313</BUDGET>
				<PAY>193</PAY>
			</PASSING>
			<PAGES>24</PAGES>
			<CITY>Гомель</CITY>
		</POIT>
		<POIT>
			<UNIVERSITY>Белорусский государственный технологический университет</UNIVERSITY>
			<PASSING>
				<BUDGET>305</BUDGET>
				<PAY>220</PAY>
			</PASSING>
			<PAGES>90</PAGES>
			<CITY>Минск</CITY>
		</POIT>
		<POIT>
			<UNIVERSITY>Белорусский государственный университет информатики и радиоэлектроники</UNIVERSITY>
			<PASSING>
				<BUDGET>371</BUDGET>
				<PAY></PAY>
			</PASSING>
			<PAGES>180</PAGES>
			<CITY>Минск</CITY>
		</POIT>
	</SPECIALIZATION>
